name: "I2C OLED Display for SSD1306, SSD1309"
description: "This addon lets you display to your I2C OLED for a Raspberry Pi with an I2C SSD1306 0.91\" 128x32 and SSD1309 128x64 OLED."
version: "82a7852"
slug: "i2c_oled_display"
startup: services
boot: manual
hassio_api: true
homeassistant_api: true
init: false
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - media:rw
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
options:
  Show_Status_Screen: true

  Default_Duration: 1
  DateTime_Format: "%d/%m/%Y %H:%M:%S"
  Static_Screen_Text_NoScroll: false
  Temperature_Unit: "C"
  Rotate: 0

  Status_Screen_Duration: 1
  Status_Screen_Limit: 0

  Debug_Mode: false
  I2C_bus: 1
  Screenshot: ''
  Driver: 'SSD1306'

schema:
  Show_Status_Screen: bool

  Default_Duration: int
  DateTime_Format: "str?"
  Static_Screen_Text_NoScroll: bool
  Temperature_Unit: "list(C|F)?"
  Rotate: "int?"

  Status_Screen_Duration: "int?"
  Status_Screen_Limit: "int?"

  Debug_Mode: bool
  I2C_bus: "int(0,20)"
  Screenshot: "list(|/media)"
  Driver: "list(SSD1306|SSD1309)"
